jobs:
  build:
    environment:
      COMMERCE_SDK_INPUT_DIR: ./test/raml/valid/
    working_directory: ~/build_only
    executor:
      name: node/default
      tag: '10.16'
    
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run build
      - run: npm run test
      - run: npm run test:integration
      - store_test_results:
          path: reports

  build-12:
    working_directory: ~/build_only
    environment:
      COMMERCE_SDK_INPUT_DIR: ./test/raml/valid/
    executor:
      name: node/default
      tag: '12.14'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run build
      - run: npm run test
      - run: npm run test:integration
      - store_test_results:
          path: reports

  publish:
    working_directory: ~/build_and_publish
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run build
      - run:
          name: Create npmrc file to authenticate with npm registry.
          command: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
      - run: npm run publish
workflows:
  version: 2
  build-and-test:
    filters:
      tags:
        ignore: /^v.*/
    jobs:
      - build
      - build-12
  build-test-deploy:
    filters:
      tags:
        only: /^v.*/
    jobs:
      - build
      - build-12
      - confirm-publish-if-tagged:
          type: approval
          requires:
            - build
            - build-12
      - publish:
          requires:
            - confirm-publish-if-tagged


orbs:
  node: circleci/node@1.1
version: 2.1

