jobs:
  build:
    working_directory: ~/build_only
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run build
      - run: npm run test
      - run: npm run test:integration
      - store_test_results:
          path: reports

  build-12:
    working_directory: ~/build_only
    executor:
      name: node/default
      tag: '12.14'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run build
      - run: npm run test
      - run: npm run test:integration
      - store_test_results:
          path: reports

  publish:
    working_directory: ~/build_and_publish
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run build
      - run:
          name: Create npmrc file to authenticate with npm registry.
          command: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
      - run: npm run publish
workflows:
  version: 2
          
  build-test-deploy:
    jobs:
      - build
      - build-12
      - hold:
        filters:
          tags:
            only: /^v.*/
        type: approval
        requires:
          - build
          - build-12
      - publish:
          requires:
            - hold


orbs:
  node: circleci/node@1.1
version: 2.1

