
workflows:
  version: 2
  test:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run :
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install npm wee
          command: npm install
      - run:
          name: Install npm wee
          command: npm run build
      - run:
          name: build
          command: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage