version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.16.0

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Update NPM to the latest
          command: "sudo npm install -g npm@latest"

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Build application
          command: npm run build

      - run:
          name: Test application
          command: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test