#%RAML 1.0
title: SCAPI
version: v1
mediaType: application/json
protocols: HTTPS
baseUri: https://{shortCode}.api.commercecloud.salesforce.com/custom/scapi/{version}
baseUriParameters:
  shortCode:
    description: A region-specific merchant identifier.
    example: 0dnz6oep
    pattern: ^([a-z0-9]+)(-[a-z0-9]+)*$

description: This is the 64labs Custom API.

uses:
  ApiStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/api-standards/1.1.15/api-standards.raml
  CommerceCloudStandards: exchange_modules/893f605e-10e2-423a-bdb4-f952f56eb6d8/commerce-cloud-standards/1.0.27/commerce-cloud-standards.raml

/organizations/{organizationId}:
  type: CommerceCloudStandards.Organization

  /active-payment-methods:
    get:     
      description: 'Hello Dave 1.' 
      displayName: getActivePaymentMethods      
      is:
        - CommerceCloudStandards.SiteSpecific:
      # queryParameters:
      responses:
        '200':
          description: Success.
          body:
            application/json:
              type: object
      securedBy:
        - CommerceCloudStandards.ShopperToken: { scopes: [sfcc.shopper-products] }

  /customer-groups:
    get:     
      description: 'Hello Dave 1.' 
      displayName: getCustomerGroups      
      is:
        - CommerceCloudStandards.SiteSpecific:
      # queryParameters:
      responses:
        '200':
          description: Success.
          body:
            application/json:
              type: ProductResult
              examples:
                product_result: !include Examples/product-result-example.raml
      securedBy:
        - CommerceCloudStandards.ShopperToken: { scopes: [sfcc.shopper-products] }

  /site-preferences:
    get:     
      description: 'Hello Dave 1.' 
      displayName: getSitePreferences      
      is:
        - CommerceCloudStandards.SiteSpecific:
      # queryParameters:
      responses:
        '200':
          description: Success.
          body:
            application/json:
              type: ProductResult
              examples:
                product_result: !include Examples/product-result-example.raml
      securedBy:
        - CommerceCloudStandards.ShopperToken: { scopes: [sfcc.shopper-products] }        